FROM continuumio/miniconda3:4.12.0

WORKDIR /usr/src/app

COPY environment.yml .

RUN conda env create -f environment.yml

ENV PATH="/opt/conda/envs/nyc-taxi/bin/:${PATH}"
ENV CONDA_DEFAULT_ENV nyc-taxi
ENV CONDA_PREFIX /opt/conda/env/nyc-taxi

EXPOSE 8800