name: nyc-taxi
channels:
  - conda-forge
dependencies:
  - python==3.9.15
  - pandas==1.5.2
  - pyarrow
  - fastparquet==2022.12.0
  - requests==2.28.1
  - make==4.3
  - pgcli==3.5.0
  - sqlalchemy==1.4.46
  - google-api-python-client
  - gcsfs
  - pandas-gbq
  - psycopg2-binary==2.9.3
  - jupyter==1.0.0
  # Pip
  - pip==22.3.1
  - pip:
    - dbt-postgres
