name: nyc-taxi
channels:
  - conda-forge
dependencies:
  - python==3.8.16
  - pandas==1.5.2
  - pyarrow==8.0.1
  - fastparquet==2022.12.0
  - requests==2.28.1
  - make==4.3
  - gcsfs==2022.11.0
  - pandas-gbq==0.17.9
  - jupyter==1.0.0
  # Pip
  - pip==22.3.1
  - pip:
    - dbt-bigquery==1.3.0
