name: trip-duration
channels:
  - conda-forge
dependencies:
  - python==3.9.15
  - pandas==1.5.2
  - fastparquet
  - requests==2.28.1
  - make
  - pgcli
  - sqlalchemy
  - psycopg2-binary
  - jupyter==1.0.0
  # Pip
  - pip==22.3.1
  - pip:
