version: 2

sources:
    - name: public
      tables:
        - name: green_taxi
          description: "Green taxi trip data"
        - name: yellow_taxi
          description: "Yellow taxi trip data"
